# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0019_auto_20180908_1724'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0437\u0430\u043c\u043e\u0432\u043b\u0435\u043d\u043d\u044f')),
                ('total_sum', models.IntegerField(verbose_name='\u041a\u043e\u0448\u0442\u043e\u0440\u0438\u0441\u043d\u0430 \u0432\u0430\u0440\u0442\u0456\u0441\u0442\u044c')),
                ('paid_sum', models.IntegerField(default=0, verbose_name='\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u0430 \u0432\u0430\u0440\u0442\u0456\u0441\u0442\u044c')),
                ('done_sum', models.IntegerField(default=0, verbose_name='\u0412\u0430\u0440\u0442\u0456\u0441\u0442\u044c \u0432\u0438\u043a\u043e\u043d\u0430\u043d\u0438\u0445 \u0440\u043e\u0431\u0456\u0442')),
                ('tasks_number', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u0456\u043b\u044c\u043a\u0456\u0441\u0442\u044c \u043d\u0435\u043e\u0431\u0445\u0456\u0434\u043d\u0438\u0445 \u0442\u0430\u0441\u043a\u0456\u0432')),
                ('status', models.CharField(choices=[('active', '\u0410\u043a\u0442\u0438\u0432\u043d\u0435'), ('inactive', '\u041f\u0440\u0438\u0437\u0443\u043f\u0438\u043d\u0435\u043d\u0435'), ('done', '\u0412\u0438\u043a\u043e\u043d\u0430\u043d\u0435')], max_length=256, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0432\u0438\u043a\u043e\u043d\u0430\u043d\u043d\u044f')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freports.Report', verbose_name='\u041f\u0440\u043e\u0432\u0430\u0434\u0436\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043c\u043e\u0432\u043b\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0417\u0430\u043c\u043e\u0432\u043b\u0435\u043d\u043d\u044f',
            },
        ),
    ]
