# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20181111_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0440\u0438\u043c\u0430\u043d\u043d\u044f')),
                ('amount', models.IntegerField(verbose_name='\u0421\u0443\u043c\u0430')),
                ('payer', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041f\u043b\u0430\u0442\u043d\u0438\u043a')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account', verbose_name='\u0426\u0456\u043b\u044c\u043e\u0432\u0438\u0439 \u0440\u0430\u0445\u0443\u043d\u043e\u043a')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Order', verbose_name='\u0417\u0430\u043c\u043e\u0432\u043b\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0434\u0445\u043e\u0434\u0436\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u041d\u0430\u0434\u0445\u043e\u0434\u0436\u0435\u043d\u043d\u044f',
            },
        ),
    ]
