# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tasks_number',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041a\u0456\u043b\u044c\u043a\u0456\u0441\u0442\u044c \u043d\u0435\u043e\u0431\u0445\u0456\u0434\u043d\u0438\u0445 \u0442\u0430\u0441\u043a\u0456\u0432'),
        ),
    ]
