# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20190316_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_sum',
        ),
    ]
