# Generated by Django 3.0.5 on 2020-05-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20200328_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Account', verbose_name='Цільовий рахунок'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Account', verbose_name='Цільовий рахунок'),
        ),
        migrations.AlterField(
            model_name='income',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Order', verbose_name='Замовлення'),
        ),
    ]
