# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('plaintiff', models.CharField(max_length=128)),
                ('defendant', models.CharField(max_length=128)),
                ('object_name', models.CharField(max_length=128)),
                ('research_kind', models.CharField(max_length=128)),
            ],
        ),
    ]
