# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicreport',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
