# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevents',
            name='address',
            field=models.TextField(blank=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430 \u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0412\u0430\u0440\u0442\u0456\u0441\u0442\u044c \u0432\u0438\u0441\u043d\u043e\u0432\u043a\u0443'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0443\u0445\u0432\u0430\u043b\u0438'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='necessary',
            field=models.TextField(blank=True, verbose_name='\u0417\u043c\u0456\u0441\u0442 \u043a\u043b\u043e\u043f\u043e\u0442\u0430\u043d\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='received',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u0442\u0440\u0438\u043c\u0430\u043d\u0456 \u043c\u0430\u0442\u0435\u0440\u0456\u0430\u043b\u0438'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='sending',
            field=models.TextField(blank=True, verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0456 \u043c\u0430\u0442\u0435\u0440\u0456\u0430\u043b\u0438'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='subspecies',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u041f\u0456\u0434\u0432\u0438\u0434 \u043f\u043e\u0434\u0456\u0457'),
        ),
        migrations.AddField(
            model_name='reportevents',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0442\u0430 \u0447\u0430\u0441 \u043e\u0433\u043b\u044f\u0434\u0443'),
        ),
    ]
