# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0002_auto_20171218_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
