# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0002_forensicreport_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicreport',
            name='data_arrived',
            field=models.DateField(default=datetime.datetime(2017, 10, 12, 8, 52, 18, 326582, tzinfo=utc)),
        ),
    ]
