# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0002_auto_20171031_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportevents',
            name='sending',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0456 \u043c\u0430\u0442\u0435\u0440\u0456\u0430\u043b\u0438'),
        ),
    ]
