# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0003_auto_20171218_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDaysInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(default=django.utils.timezone.now)),
                ('active_days', models.IntegerField(blank=True, null=True)),
                ('waiting_days', models.IntegerField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freports.Report', verbose_name='\u0412\u0438\u0441\u043d\u043e\u0432\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u0414\u043d\u0456 \u0443 \u0432\u0438\u043a\u043e\u043d\u0430\u043d\u043d\u0456',
                'verbose_name_plural': '\u0414\u043d\u0456 \u0443 \u0432\u0438\u043a\u043e\u043d\u0430\u043d\u043d\u0456',
            },
        ),
    ]
