# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0003_auto_20171031_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=256, verbose_name="\u0412\u0438\u0434 \u043e\u0431'\u0454\u043a\u0442\u0443")),
                ('settlement', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0439 \u043f\u0443\u043d\u043a\u0442')),
                ('region', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0420\u0430\u0439\u043e\u043d \u043e\u0431\u043b\u0430\u0441\u0442\u0456')),
                ('street', models.CharField(max_length=256, verbose_name='\u0412\u0443\u043b\u0438\u0446\u044f')),
                ('building', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0431\u0443\u0434\u0438\u043d\u043a\u0443')),
                ('flat', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0438')),
                ('research_type', models.CharField(max_length=256, verbose_name="\u0422\u0438\u043f \u0434\u043e\u0441\u043b\u0456\u0434\u0436\u0435\u043d\u043d\u044f \u043e\u0431'\u0454\u043a\u0442\u0443")),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freports.Report', verbose_name='\u0412\u0438\u0441\u043d\u043e\u0432\u043e\u043a')),
            ],
            options={
                'verbose_name': "\u041e\u0431'\u0454\u043a\u0442 \u0434\u043e\u0441\u043b\u0456\u0434\u0436\u0435\u043d\u043d\u044f",
                'verbose_name_plural': "\u041e\u0431'\u0454\u043a\u0442\u0438 \u0434\u043e\u0441\u043b\u0456\u0434\u0436\u0435\u043d\u043d\u044f",
            },
        ),
    ]
