# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0004_auto_20171012_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicreport',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
