# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0004_reportsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='case_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
