# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0005_report_case_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0441\u0443\u0434\u0443')),
                ('number', models.IntegerField(verbose_name='\u041a\u043e\u0434 \u0441\u043f\u0440\u0430\u0432')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=256, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435')),
                ('first_name', models.CharField(max_length=256, verbose_name="\u0406\u043c'\u044f")),
                ('second_name', models.CharField(max_length=256, verbose_name="\u0406\u043c'\u044f \u043f\u043e \u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456")),
                ('personal_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041e\u0441\u043e\u0431\u0438\u0441\u0442\u0438\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('work_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0420\u043e\u0431\u043e\u0447\u0438\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0414\u043e\u043c\u0430\u0448\u043d\u044f \u0430\u0434\u0440\u0435\u0441\u0430')),
                ('court_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freports.Court', verbose_name='\u0421\u0443\u0434')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='chair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freports.Judge', verbose_name='\u0413\u043e\u043b\u043e\u0432\u0430 \u0441\u0443\u0434\u0443'),
        ),
    ]
