# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0005_forensicreport_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicreport',
            name='data_executed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
