# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0006_forensicreport_data_executed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forensicreport',
            old_name='data_executed',
            new_name='date_executed',
        ),
    ]
