# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0006_auto_20171222_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='days_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freports.ReportDaysInfo'),
        ),
    ]
