# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0006_auto_20171109_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u0434 \u0441\u043f\u0440\u0430\u0432'),
        ),
    ]
