# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0007_auto_20171013_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0434\u0456\u0457')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u043f\u043e\u0434\u0456\u0457')),
                ('info', models.CharField(blank=True, max_length=256, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f')),
            ],
            options={
                'verbose_name': '\u0414\u0435\u0442\u0430\u043b\u044c\u043d\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f',
                'verbose_name_plural': '\u0414\u0435\u0442\u0430\u043b\u044c\u043d\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f',
            },
        ),
        migrations.RenameModel(
            old_name='ForensicReport',
            new_name='Report',
        ),
        migrations.AddField(
            model_name='reportdetails',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freports.Report', verbose_name='\u0412\u0438\u0441\u043d\u043e\u0432\u043e\u043a'),
        ),
    ]
