# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0007_auto_20171109_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0441\u0443\u0434\u0443'),
        ),
    ]
