# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0007_auto_20171222_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='days_info',
        ),
        migrations.AddField(
            model_name='report',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='waiting_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReportDaysInfo',
        ),
    ]
