# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0008_auto_20171109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.BooleanField(),
        ),
    ]
