# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0008_auto_20171015_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetails',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freports.Report', verbose_name='\u0412\u0438\u0441\u043d\u043e\u0432\u043e\u043a'),
        ),
    ]
