# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0008_auto_20171223_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 23, 11, 14, 58, 373082)),
        ),
    ]
