# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0009_auto_20171110_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
