# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0010_auto_20171110_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='judge_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freports.Court', verbose_name='\u0421\u0443\u0434\u0434\u044f'),
        ),
    ]
