# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0010_auto_20171016_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetails',
            name='activate',
            field=models.NullBooleanField(),
        ),
    ]
