# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0011_reportdetails_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='number_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='number',
            field=models.IntegerField(),
        ),
    ]
