# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0012_auto_20171023_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='number_year',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
