# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0013_auto_20180403_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0440\u0430\u0445\u0443\u043d\u043a\u0443')),
                ('total_sum', models.IntegerField(verbose_name='\u0421\u0443\u043c\u0430 \u043d\u0430 \u0440\u0430\u0445\u0443\u043d\u043a\u0443')),
                ('cash', models.BooleanField(verbose_name='\u0413\u043e\u0442\u0456\u0432\u043a\u0430')),
                ('status', models.CharField(choices=[('self', '\u041e\u0441\u043e\u0431\u0438\u0441\u0442\u0438\u0439'), ('work', '\u0420\u043e\u0431\u043e\u0447\u0438\u0439')], max_length=256, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0440\u0430\u0445\u0443\u043d\u043a\u0443')),
                ('credit_cash', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u0448\u0442\u0438 \u0432 \u043a\u0440\u0435\u0434\u0438\u0442\u0430\u0445')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0445\u0443\u043d\u043e\u043a',
                'verbose_name_plural': '\u0420\u0430\u0445\u0443\u043d\u043a\u0438',
            },
        ),
    ]
