# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0014_auto_20171024_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportparticipants',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="\u0406\u043c'\u044f \u0442\u0430 \u043f\u043e-\u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456"),
        ),
        migrations.AlterField(
            model_name='reportparticipants',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435'),
        ),
    ]
