# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0016_task_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
