# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0017_report_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='status',
            field=models.CharField(max_length=256, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0432 \u043f\u0440\u043e\u0432\u0430\u0434\u0436\u0435\u043d\u043d\u0456'),
        ),
    ]
