# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0018_auto_20180905_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
