# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0019_auto_20180908_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('number_year', models.CharField(max_length=128, null=True)),
                ('address', models.CharField(max_length=128)),
                ('object_name', models.CharField(max_length=128)),
                ('research_kind', models.CharField(max_length=128)),
                ('active', models.NullBooleanField()),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('date_arrived', models.DateField(default=django.utils.timezone.now)),
                ('executed', models.BooleanField(default=False)),
                ('date_executed', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(default=django.utils.timezone.now)),
                ('active_days_amount', models.IntegerField(default=0)),
                ('applicant', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
