# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0020_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='addition_info',
            field=models.TextField(blank=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f'),
        ),
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.NullBooleanField(verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0438\u0439 \u0441\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(max_length=128, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_name',
            field=models.CharField(max_length=128, verbose_name="\u041d\u0430\u0437\u0432\u0430 \u043e\u0431'\u0454\u043a\u0442\u0430"),
        ),
        migrations.AlterField(
            model_name='report',
            name='research_kind',
            field=models.CharField(max_length=128, verbose_name='\u0412\u0438\u0434 \u0434\u043e\u0441\u043b\u0456\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='research',
            name='active',
            field=models.NullBooleanField(verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0438\u0439 \u0441\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='research',
            name='address',
            field=models.CharField(max_length=128, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='research',
            name='applicant',
            field=models.CharField(max_length=128, verbose_name='\u0417\u0430\u043c\u043e\u0432\u043d\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='research',
            name='object_name',
            field=models.CharField(max_length=128, verbose_name="\u041d\u0430\u0437\u0432\u0430 \u043e\u0431'\u0454\u043a\u0442\u0430"),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_kind',
            field=models.CharField(max_length=128, verbose_name='\u0412\u0438\u0434 \u0434\u043e\u0441\u043b\u0456\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
    ]
