# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0022_auto_20190202_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='addition_info',
            field=models.TextField(blank=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f'),
        ),
    ]
