# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0023_auto_20190316_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
