# Generated by Django 3.0.5 on 2020-05-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0024_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='court_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freports.Court', verbose_name='Суд'),
        ),
        migrations.AlterField(
            model_name='report',
            name='judge_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freports.Judge', verbose_name='Суддя'),
        ),
        migrations.AlterField(
            model_name='reportevents',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freports.Report', verbose_name='Висновок'),
        ),
        migrations.AlterField(
            model_name='reportparticipants',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freports.Report', verbose_name='Висновок'),
        ),
    ]
