# Generated by Django 3.0.5 on 2020-05-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0025_auto_20200503_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportevents',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freports.Report', verbose_name='Висновок'),
        ),
    ]
