# Generated by Django 3.1.7 on 2021-04-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0026_auto_20200503_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='additional_report',
            field=models.BooleanField(blank=True, null=True, verbose_name='Додаткова експертиза'),
        ),
        migrations.AddField(
            model_name='report',
            name='repeater_report',
            field=models.BooleanField(blank=True, null=True, verbose_name='Повторна експертиза'),
        ),
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.BooleanField(null=True, verbose_name='Активний статус'),
        ),
        migrations.AlterField(
            model_name='reportevents',
            name='activate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='active',
            field=models.BooleanField(null=True, verbose_name='Активний статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='execute',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус виконання'),
        ),
    ]
