# Generated by Django 3.1.7 on 2021-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0027_auto_20210403_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevents',
            name='way_forwart',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Спосіб пересилання'),
        ),
    ]
