# Generated by Django 3.1.7 on 2021-04-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freports', '0028_reportevents_way_forwart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportevents',
            old_name='way_forwart',
            new_name='way_forward',
        ),
    ]
